### ISSUE TITLE
Problem: Resources about Kata are missing

### ISSUE THREAD

**Issue by gabm** [TUC-NT-DF/student-guide#2]
We need to mention resources that explain Kata and highlight how the marvin bot is working.

- [x] find and link kata resources
- [x] document how the marvin bot is working

**Comment by gabm** [comment]
@aswin-roman: could you have a look into this?

**Comment by aswin-roman** [comment]
Among the reading materials that were shared with me (during my onboarding) were these links: 
1. http://pc-nobi.etit.tu-chemnitz.de/userguide/ - Environment setup (Not working anymore...)
2. https://draive.com/link_dev/guide/ - Draive link2 node (Could read it, some info on conda etc are available)

Some other material was also there but unfortunately I am not able to find them. 


Some General Info, I found on KATA: 
1. https://www.gembaacademy.com/resources/gemba-glossary/kata 
2. https://www.lean.org/the-lean-post/articles/the-toyota-way-and-toyota-kata-how-do-they-fit/

**Comment by gabm** [comment]
thx.. can you pls add to the guide via PR?

**Comment by plihub** [comment]
@duttakriti added Marvin documentation, thank you.

This issue can be closed.
